[package]
edition = "2021"
name = "examples"
version = "0.1.0"

[dependencies]
blockifier = { workspace = true }
cairo-vm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

snos = { path = "../../" }
clap = { version = "4.5.4", features = ["derive"] }

[[bin]]
name = "hint_tool"
path = "src/main.rs"
