[workspace]
members = ["cairo-type-derive", "bin/hint_tool"]
resolver = "2"

[package]
edition = "2021"
name = "snos"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.75"
assert_matches = "1.5.0"
async-stream = "0.3.5"
base64 = "0.21.3"
bitvec = { version = "1.0.1", features = ["serde"] }
blockifier = { git = "https://github.com/keep-starknet-strange/blockifier", branch = "snos/callinfo-clone", features = ["clone", "testing"] }
cairo-type-derive = { version = "0.1.0", path = "cairo-type-derive" }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", features = ["extensive_hints", "cairo-1-hints"] }
futures = "0.3.30"
futures-util = "0.3.30"
getset = "0.1.2"
heck = "0.4.1"
hex = "0.4.3"
indexmap = "1.9.2"
indoc = "2"
lazy_static = "1.4.0"
log = "0.4.19"
num-bigint = "0.4"
num-integer = "0.1.45"
num-traits = "0.2.16"
regex = "1.10.0"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.105", features = ["arbitrary_precision"] }
serde_with = "3.3.0"
serde_yaml = "0.9.25"
starknet-crypto = "0.6.0"
starknet_api = { version = "=0.7.0-dev.0", features = ["testing"] }
thiserror = "1.0.48"
tokio = { version = "1.36.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.14"
uuid = { version = "1.4.0", features = ["v4", "serde"] }
zip = { version = "0.6.6", features = ["deflate-zlib"] }

# These dependencies pin cairo-lang requirement versions because cairo-vm does not do it
cairo-lang-starknet = { version = "~2.5.4" }
cairo-lang-casm = { version = "~2.5.4" }
cairo-lang-defs = { version = "~2.5.4" }
cairo-lang-diagnostics = { version = "~2.5.4" }
cairo-lang-filesystem = { version = "~2.5.4" }
cairo-lang-semantic = { version = "~2.5.4" }
cairo-lang-sierra = { version = "~2.5.4" }
cairo-lang-syntax = { version = "~2.5.4" }

[dependencies]
anyhow = { workspace = true }
assert_matches = { workspace = true }
async-stream = { workspace = true }
base64 = { workspace = true }
bitvec = { workspace = true }
blockifier = { workspace = true }
cairo-type-derive = { workspace = true }
cairo-vm = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
getset = { workspace = true }
heck = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
num-bigint = { workspace = true }
num-integer = { workspace = true }
num-traits = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
serde_yaml = { workspace = true }
starknet-crypto = { workspace = true }
starknet_api = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
uuid = { workspace = true }
zip = { workspace = true }

# These dependencies pin cairo-lang requirement versions because cairo-vm does not do it
cairo-lang-starknet = { workspace = true }
cairo-lang-casm = { workspace = true }
cairo-lang-defs = { workspace = true }
cairo-lang-diagnostics = { workspace = true }
cairo-lang-filesystem = { workspace = true }
cairo-lang-semantic = { workspace = true }
cairo-lang-sierra = { workspace = true }
cairo-lang-syntax = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4.0"
rand = "0.8.5"
rstest = "0.18.2"
